<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulaire</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link rel="stylesheet" href="./css/style.css">
</head>

<body>
    <form action="" method="post" enctype="multipart/form-data">
        <div class="wrapper rounded bg-white">

            <div class="h3">Mise a jours des informations</div>

            <div class="form">
                <div class="row">
                    <div class="col-md-6 mt-md-0 mt-3">
                        <?php foreach (List_Info() as $key) : ?>
                            <label>Nom</label>
                            <input name="Nom" type="text" class="form-control" value="<?= $key['Nom'] ?>" required>
                    </div>
                    <div class="col-md-6 mt-md-0 mt-3">
                        <label>Prénom</label>
                        <input name="Prénom" type="text" class="form-control" value="<?= $key['Prénom'] ?>" required>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mt-md-0 mt-3">
                        <label>Adresse</label>
                        <input name="Adresse" type="text" class="form-control" value="<?= $key['Adresse'] ?>" required>
                    </div>
                    <div class="col-md-6 mt-md-0 mt-3">
                        <label>Tel</label>
                        <input name="Tel" type="text" class="form-control" value="<?= $key['Tel'] ?>" required>
                    </div>
                    <div class="col-md-6 mt-md-0 mt-3">
                        <label>Image</label>
                        <input name="file" type="file" class="form-control" value="<?= $key['Image'] ?>" required>
                    </div>
                <?php endforeach ?>
                </div>
            </div>
            <div class="btnSave"><button name="save" type="submit">Save</button></div>
        </div>

        </div>
</body>

</html>